version: '3.5'

services:
  portfolio:
    image: mcodegeeks/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    networks:
      - postgres_network
      - nginx_network
    ports:
      - 8000:8000
    volumes:
      - static_volume:/var/www/staticfiles/
      - media_volume:/var/www/mediafiles/      
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - postgres_network
    ports:
      - "54320:5432"
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env.postgres
  nginx:
    image: mcodegeeks/nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - nginx_network
    ports:
      - 80:80
    volumes:
      - static_volume:/var/www/staticfiles/
      - media_volume:/var/www/mediafiles/
    depends_on:
      - portfolio

volumes:
  postgres_volume:
  static_volume:
  media_volume:

networks:
  postgres_network:
    driver: bridge
  nginx_network:
    driver: bridge