version: '3.5'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - postgres_network    
    ports:
      - "54320:5432"
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env.postgres

volumes:
  postgres_volume:

networks:
  postgres_network:
    driver: bridge