version: '3.7'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    image: web:custom
    container_name: web
    restart: unless-stopped
    command: gunicorn site_mgr.wsgi:application --bind 0.0.0.0:8000
    networks:
      - postgres_network
      - nginx_network
    volumes:
      - static_data:/home/app/web/staticfiles
      - media_data:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - postgres_network
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env.prod.postgres
  nginx:
    build: ./nginx
    image: nginx:custom
    container_name: nginx
    restart: unless-stopped
    networks:
      - nginx_network
    volumes:
      - static_data:/home/app/web/staticfiles
      - media_data:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
    external: true
  static_data:
    external: true
  media_data:
    external: true

networks:
  postgres_network:
    driver: bridge
  nginx_network:
    driver: bridge